const { chromium } = require('/home/claude/.npm-global/lib/node_modules/playwright');
const MOCK = process.argv.includes('--ai');
(async () => {
  const b = await chromium.launch();
  const ctx = await b.newContext({ viewport: { width: 1440, height: 900 }, acceptDownloads: true });
  const p = await ctx.newPage();
  const errs = [];
  p.on('pageerror', e => errs.push('pageerror: ' + e.message));
  p.on('console', m => { if (m.type() === 'error' && !m.text().includes('ERR_TUNNEL')) errs.push('console: ' + m.text()); if (m.text().startsWith('[mock]')) console.log(m.text()); });
  if (MOCK) await p.addInitScript({ path: 'test/mock-sample.js' });
  const base = 'http://127.0.0.1:8765/dist/index.html';
  const tag = MOCK ? 'ai' : 'rules';
  const shot = async (name) => { await p.waitForTimeout(600); await p.screenshot({ path: `test/shots/${tag}-${name}.png` }); };
  await p.goto(base + '#/signup');
  await p.fill('#su-name', 'Usuario Prueba'); await p.fill('#su-company', 'Costa Serveis SL'); await p.fill('#su-email', 'j@test.com'); await p.fill('#su-pass', 'password123');
  await p.selectOption('#su-ind', 'Limpieza y facility services');
  await p.click('button:has-text("Crear cuenta")');
  await p.click('button:has-text("Continuar")');
  // onboarding: details
  await p.fill('#ob-legal', 'Costa Serveis SL'); await p.fill('#ob-rev', '2,1 M€ (2025)'); await p.fill('#ob-desc', 'Limpieza y mantenimiento de instalaciones deportivas y edificios públicos en la costa de Barcelona.');
  await p.click('text=Guardar y continuar');
  await p.click('button:has-text("Continuar")'); // docs
  await p.fill('#pp-t', 'Limpieza de piscinas municipales'); await p.fill('#pp-c', 'Ajuntament de Sitges'); await p.fill('#pp-y', '2022–2025'); await p.fill('#pp-v', '210.000 € / año');
  await p.click('button:has-text("Añadir proyecto")'); await p.click('button:has-text("Continuar")');
  await p.click('text=ISO 9001 — Gestión de la calidad'); await p.click('button:has-text("Continuar")');
  await shot('01-ready');
  await p.click('text=Subir un pliego');
  await p.waitForSelector('text=Usar un pliego de ejemplo');
  await p.click('text=Usar un pliego de ejemplo');
  await p.waitForSelector('text=Pliego de ejemplo — Mantenimiento de instalaciones deportivas.pdf');
  await shot('02-new');
  await p.click('button:has-text("Analizar documentos")');
  await shot('03-analyzing');
  await p.waitForSelector('text=Análisis completado', { timeout: 60000 });
  await shot('04-complete');
  await p.click('text=Revisar requisitos');
  await shot('05-reqs');
  await p.click('.tab:has-text("Resumen")'); await shot('06-overview');
  await p.click('.tab:has-text("Criterios")'); await shot('07-criteria');
  await p.click('.tab:has-text("Propuesta")');
  await p.click('button:has-text("Generar borrador") >> nth=0');
  await p.waitForTimeout(2500);
  await shot('08-proposal');
  await p.click('button:has-text("Pregunta a PROPO")');
  await p.click('text=¿Qué podría causar nuestra exclusión?');
  await p.waitForTimeout(2500);
  await shot('09-chat');
  await p.click('.tab:has-text("Paquete")');
  const [dl] = await Promise.all([p.waitForEvent('download', { timeout: 20000 }).catch(e => null), p.click('text=Descargar paquete de presentación')]);
  if (dl) { const path = 'test/package-' + tag + '.zip'; await dl.saveAs(path); console.log('downloaded', path); } else console.log('no download');
  await shot('10-package');
  const st = await p.evaluate(() => JSON.parse(localStorage.getItem('propo:state:v1')));
  const pr = st.projects[0];
  console.log('mode', pr.analysis.mode, 'reqs', pr.requirements.length, 'crit', pr.criteria.length, 'sections', pr.sections.length, 'deadline', pr.analysis.deadline);
  console.log(pr.requirements.map(r => `${r.status.padEnd(10)} ${r.category.padEnd(14)} ${r.uncertain?'U':' '} ${r.title}`).join('\n'));
  console.log(pr.criteria.map(c => `${c.points} ${c.kind} ${c.name}`).join('\n'));
  console.log(pr.sections.map(s => `${s.status} ${s.title}`).join('\n'));
  console.log(errs.join('\n') || 'no errors');
  await b.close();
})();
