const { chromium } = require('/home/claude/.npm-global/lib/node_modules/playwright');
(async () => {
  const b = await chromium.launch();
  const ctx = await b.newContext({ viewport: { width: 1440, height: 900 } });
  const p = await ctx.newPage();
  const errs = [];
  p.on('pageerror', e => errs.push('pageerror: ' + e.message));
  p.on('console', m => { if (m.type() === 'error' && !/ERR_TUNNEL|fonts\.g/.test(m.text())) errs.push('console: ' + m.text()); });
  const base = 'http://127.0.0.1:8765/dist/index.html';
  const shot = async (name) => { await p.waitForTimeout(700); await p.screenshot({ path: `test/shots/${name}.png` }); };
  await p.goto(base); await shot('01-landing');
  await p.evaluate(() => window.scrollTo(0, 1500)); await shot('02-landing-mid');
  await p.evaluate(() => window.scrollTo(0, 3000)); await shot('02b-landing-low');
  await p.goto(base + '#/pricing'); await shot('03-pricing');
  await p.goto(base + '#/signup'); await shot('04-signup');
  await p.fill('#su-name', 'Usuario Prueba'); await p.fill('#su-company', 'Test Catering SL'); await p.fill('#su-email', 'j@test.com'); await p.fill('#su-pass', 'password123');
  await p.selectOption('#su-ind', 'Catering y restauración');
  await p.click('button:has-text("Crear cuenta")'); await shot('05-welcome');
  await p.click('text=1–3 al mes'); await p.click('button:has-text("Continuar")'); await shot('06-onboarding');
  await p.click('text=Saltar configuración'); await shot('07-dashboard');
  await p.goto(base + '#/app/tenders'); await shot('07b-tenders');
  await p.click('.t-row >> nth=0'); await shot('07c-tender-drawer');
  await p.goto(base + '#/app/projects/p_sample'); await shot('08-project');
  await p.goto(base + '#/app/projects/p_sample/requirements'); await shot('09-reqs');
  await p.goto(base + '#/app/projects/p_sample/proposal'); await shot('10-proposal');
  await p.goto(base + '#/app/projects/p_sample/criteria'); await shot('11-criteria');
  await p.goto(base + '#/app/projects/p_sample/compliance'); await shot('12-compliance');
  await p.goto(base + '#/app/projects/p_sample/package'); await shot('13-package');
  await p.goto(base + '#/app/company'); await shot('14-company');
  await p.goto(base + '#/app/company/search'); await shot('14b-company-search');
  await p.goto(base + '#/app/documents'); await shot('14c-vault');
  await p.goto(base + '#/app/templates'); await shot('14d-templates');
  await p.goto(base + '#/app/notifications'); await shot('14e-notifs');
  await p.goto(base + '#/app/settings/billing'); await shot('15-billing');
  await p.goto(base + '#/app/settings/privacy'); await shot('15b-privacy');
  await p.goto(base + '#/app/admin'); await shot('16-admin');
  console.log(errs.join('\n') || 'no errors');
  await b.close();
})();
